#### Подключение к диску

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd '/content/drive/My Drive/Intro to AI/LR2_prod_example/Пример2'

/content/drive/My Drive/Intro to AI/LR2_prod_example/Пример2

In [ ]:
import pandas as pd

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
df = pd.read_csv("Data.csv")
df

      F1   F2   F3   F4              F5
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
df.describe()

               F1          F2          F3          F4
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [ ]:
df.F5.value_counts()

F5
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   F1      150 non-null    float64
 1   F2      150 non-null    float64
 2   F3      150 non-null    float64
 3   F4      150 non-null    float64
 4   F5      150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
df = df[df.F5 != "Iris-virginica"]
df.F5.value_counts()

F5
Iris-setosa        50
Iris-versicolor    50
Name: count, dtype: int64

In [ ]:
clf = LogisticRegression(random_state=0)\
.fit(df[['F1', 'F2', 'F3', 'F4']].values, df['F5'].values) # clf - классификатор; .fit - обучение

In [ ]:
import numpy as np
import scipy as sp

In [ ]:
input = [[5.1,3.5,1.4,0.2], [7.0,3.2,4.7,1.4]]
input

[[5.1, 3.5, 1.4, 0.2], [7.0, 3.2, 4.7, 1.4]]

In [ ]:
a = np.asarray(input)

In [ ]:
a

array([[5.1, 3.5, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4]])

In [ ]:
a = np.random.uniform(low=0.1, high=5, size=(2,4)) * 1000

In [ ]:
a

array([[ 427.56999436, 3423.93688552, 1640.11285385, 4960.72261529],
       [2016.50100271,  140.047792  ,  662.12345212,  984.55369707]])

In [ ]:
clf.predict(a)

array(['Iris-versicolor', 'Iris-versicolor'], dtype=object)

In [ ]:
from google.colab import files

In [ ]:
import pickle
pickle.dump(clf, open('clf.pkl', 'wb'))
files.download('clf.pkl')

In [ ]:
import pickle
clf = pickle.load(open('clf.pkl', 'rb'))
clf.predict(a)

array(['Iris-setosa', 'Iris-versicolor'], dtype=object)

In [ ]:
class ModelExecutor:
  def __init__(self, model_path='clf.pkl'):
    self.model_path = model_path
    self.model = pickle.load(open(self.model_path, 'rb'))
  def predict(self, mode, input: np.ndarray = np.asarray([[5.1,3.5,1.4,0.2], [7.0,3.2,4.7,1.4]])):
    if mode == 'Hello':
      return 'Hello'
    else:
      return self.model.predict(input)

In [ ]:
if __name__ == '__main__':
  from argparse import ArgumentParser

  parser = ArgumentParser()
  parser.add_argument('--model_path', required=False, default='clf.pkl', type=str, help='Path to model file')
  parser.add_argument('--mode', required=True, type=str, help='auto or Hello')

  args = parser.parse_args()

  me = ModelExecutor(model_path=args.model_path)
  me.predict(mode=args.mode, )

In [ ]:

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--model_path', required=False, default='clf.pkl', type=str, help='Path to model file')
parser.add_argument('--mode', required=True, type=str, help='auto or Hello')

args = parser.parse_args()

me = ModelExecutor(model_path=args.model_path)
me.predict(mode=args.mode, )

usage: colab_kernel_launcher.py [-h] [--model_path MODEL_PATH] --mode MODE
colab_kernel_launcher.py: error: the following arguments are required: --mode

SystemExit: 2

/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)